### ISSUE TITLE
change axios to nightmare

### ISSUE THREAD

**Issue by mefengl** [OpenAHU/AHU-API#3]
https://github.com/segmentio/nightmare

**Comment by mefengl** [comment]
oring code:
https://github.com/OpenAHU/AHU-API/commit/ca21d67f7aa2e0d2c9d3953697dbfa3296b19c4f#diff-e1f8fd2309c93b659915f71693bd0eafcdecb60f984bdfb737853832879e5d18

**Comment by mefengl** [comment]
maybe useful:
https://www.google.com/search?q=run+electron+in+lambda&sourceid=chrome&ie=UTF-8
https://github.com/dimkir/nightmare-lambda-tutorial

**Comment by Eddy0644** [comment]
The AHU-server-side code changed and nowadays we don't need to rewrite that API anymore.
